In [1]:
import pandas as pd

In [2]:
pd.__version__

'2.2.2'

In [7]:
#Data Frame

df = pd.DataFrame([11,21,31],columns=['Col_Name'])
print(df)

   Col_Name
0        11
1        21
2        31

In [9]:
data = {
    
    'Name' : ['Andrew','Steve','Zuck','Larry'],
    'Age' : [48,58,38,30],
    'Salary': [25000,36000,45000,55000]
}

In [11]:
df = pd.DataFrame(data)
print(df)

     Name  Age  Salary
0  Andrew   48   25000
1   Steve   58   36000
2    Zuck   38   45000
3   Larry   30   55000

In [12]:
print(type(df))

<class 'pandas.core.frame.DataFrame'>

In [13]:
df.head(2)

     Name  Age  Salary
0  Andrew   48   25000
1   Steve   58   36000

In [14]:
df.tail(2)

    Name  Age  Salary
2   Zuck   38   45000
3  Larry   30   55000

In [16]:
df.shape

(4, 3)

In [17]:
df.columns

Index(['Name', 'Age', 'Salary'], dtype='object')

In [20]:
#Remaining Columns
df.rename(columns={'Salary':'Monthly_Salary'},inplace=True)

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Name            4 non-null      object
 1   Age             4 non-null      int64
 2   Monthly_Salary  4 non-null      int64
dtypes: int64(2), object(1)
memory usage: 228.0+ bytes

In [ ]:
df.describe() # Showing Statistical overview of the values

             Age  Monthly_Salary
count   4.000000        4.000000
mean   43.500000    40250.000000
std    12.151817    12789.970029
min    30.000000    25000.000000
25%    36.000000    33250.000000
50%    43.000000    40500.000000
75%    50.500000    47500.000000
max    58.000000    55000.000000

In [ ]:
#Save and Load the Data from csv

df.to_csv('Test_data.csv',index=False) #export Dataframe

In [ ]:
load_dataframe = pd.read_csv('Test_data.csv') #Load DataFrame
load_dataframe

     Name  Age  Monthly_Salary
0  Andrew   48           25000
1   Steve   58           36000
2    Zuck   38           45000
3   Larry   30           55000

In [33]:
#Rows and ColumnsSelection

df[['Name','Monthly_Salary']] # Selecting Single Column in the DataFrame

     Name  Monthly_Salary
0  Andrew           25000
1   Steve           36000
2    Zuck           45000
3   Larry           55000

In [40]:
df.loc[(df.Name == 'Zuck') & (df.Age > 30)] # Row Selection on the bases of Name.

   Name  Age  Monthly_Salary
2  Zuck   38           45000

In [35]:
df.iloc[0]

Name              Andrew
Age                   48
Monthly_Salary     25000
Name: 0, dtype: object

### Filter the Data

In [41]:
df

     Name  Age  Monthly_Salary
0  Andrew   48           25000
1   Steve   58           36000
2    Zuck   38           45000
3   Larry   30           55000

In [ ]:
df['Age'] >= 35

0     True
1     True
2     True
3    False
Name: Age, dtype: bool

In [44]:
df[df['Age'] >= 40 ]

     Name  Age  Monthly_Salary
0  Andrew   48           25000
1   Steve   58           36000

In [45]:
df[(df['Age'] >= 35) & (df['Monthly_Salary'] >= 24000)]

     Name  Age  Monthly_Salary
0  Andrew   48           25000
1   Steve   58           36000
2    Zuck   38           45000

In [47]:
df.where(df['Age'] >= 40)

     Name   Age  Monthly_Salary
0  Andrew  48.0         25000.0
1   Steve  58.0         36000.0
2     NaN   NaN             NaN
3     NaN   NaN             NaN

### Rows and Columns Operation (Update, Add, Delete)

In [48]:
df

     Name  Age  Monthly_Salary
0  Andrew   48           25000
1   Steve   58           36000
2    Zuck   38           45000
3   Larry   30           55000

In [49]:
# Add new column 
df['Team'] = ['CEO','HR','Sr Dev','Jr Dev']

In [50]:
df

     Name  Age  Monthly_Salary    Team
0  Andrew   48           25000     CEO
1   Steve   58           36000      HR
2    Zuck   38           45000  Sr Dev
3   Larry   30           55000  Jr Dev

In [51]:
df['Bonus'] = df['Monthly_Salary'] * 0.2 

df

     Name  Age  Monthly_Salary    Team    Bonus
0  Andrew   48           25000     CEO   5000.0
1   Steve   58           36000      HR   7200.0
2    Zuck   38           45000  Sr Dev   9000.0
3   Larry   30           55000  Jr Dev  11000.0

In [54]:
# Adding New Row 

df.loc[len(df)] = ['Junaid',48,25000,'Peon',400]

In [55]:
df

           Name  Age  Monthly_Salary    Team    Bonus
0        Andrew   48           25000     CEO   5000.0
1         Steve   58           36000      HR   7200.0
2          Zuck   38           45000  Sr Dev   9000.0
3         Larry   30           55000  Jr Dev  11000.0
4  Junai Ansari   48           25000    Peon    400.0
5        Junaid   48           25000    Peon    400.0

In [56]:
len(df)

6

In [62]:
#update the Value
df.loc[5,'Name'] = 'Mathew'

In [63]:
df

     Name  Age  Monthly_Salary    Team    Bonus
0  Andrew   48           25000     CEO   5000.0
1   Steve   58           36000      HR   7200.0
2    Zuck   38           45000  Sr Dev   9000.0
3   Larry   30           55000  Jr Dev  11000.0
4  Junaid   48           25000    Peon    400.0
5  Mathew   48           25000    Peon    400.0

In [64]:
df.loc[4,'Name'] = 'Stefan'

In [65]:
df

     Name  Age  Monthly_Salary    Team    Bonus
0  Andrew   48           25000     CEO   5000.0
1   Steve   58           36000      HR   7200.0
2    Zuck   38           45000  Sr Dev   9000.0
3   Larry   30           55000  Jr Dev  11000.0
4  Stefan   48           25000    Peon    400.0
5  Mathew   48           25000    Peon    400.0

In [71]:
#Updating the value using column value 
df.loc[df.Name == 'Stefan', 'Team'] = 'WardBoy'

In [72]:
df

     Name  Age  Monthly_Salary     Team    Bonus
0  Andrew   48           25000      CEO   5000.0
1   Steve   58           36000       HR   7200.0
2    Zuck   38           45000   Sr Dev   9000.0
3   Larry   30           55000   Jr Dev  11000.0
4  Stefan   48           25000  WardBoy    400.0
5  Mathew   48           25000     Peon    400.0

In [75]:
#Dropping and Deleting 

df.drop(df[df.Name == 'Mathew'].index,inplace=True)

In [76]:
df

     Name  Age  Monthly_Salary     Team    Bonus
0  Andrew   48           25000      CEO   5000.0
1   Steve   58           36000       HR   7200.0
2    Zuck   38           45000   Sr Dev   9000.0
3   Larry   30           55000   Jr Dev  11000.0
4  Stefan   48           25000  WardBoy    400.0

In [79]:
# Sort Values
df.sort_values('Age',ascending=False)

     Name  Age  Monthly_Salary     Team    Bonus
1   Steve   58           36000       HR   7200.0
0  Andrew   48           25000      CEO   5000.0
4  Stefan   48           25000  WardBoy    400.0
2    Zuck   38           45000   Sr Dev   9000.0
3   Larry   30           55000   Jr Dev  11000.0

### Working with Date Time Values

In [ ]:
df['DOJ'] = ['2024-01-02','2024-02-01','2024-05-01','2024-10-01','2024-11-01','2024-12-01']