In [2]:
import numpy as np
import pandas as pd

In [3]:
courses = pd.read_csv('courses.csv')
students = pd.read_csv('students.csv')
reg_01 = pd.read_csv('reg-month1.csv')
reg_02 = pd.read_csv('reg-month2.csv')

In [4]:
regs = pd.concat([reg_01,reg_02],ignore_index=True)

In [5]:
# Multi Index Data Frame

pd.concat([reg_01,reg_02],keys=['Nov','Dec'])

        student_id  course_id
Nov 0           23          1
    1           15          5
    2           18          6
    3           23          4
    4           16          9
    5           18          1
    6            1          1
    7            7          8
    8           22          3
    9           15          1
    10          19          4
    11           1          6
    12           7         10
    13          11          7
    14          13          3
    15          24          4
    16          21          1
    17          16          5
    18          23          3
    19          17          7
    20          23          6
    21          25          1
    22          19          2
    23          25         10
    24           3          3
Dec 0            3          5
    1           16          7
    2           12         10
    3           12          1
    4           14          9
    5            7          7
    6            7          2
    7           16          3
    8           17         10
    9           11          8
    10          14          6
    11          12          5
    12          12          7
    13          18          8
    14           1         10
    15           1          9
    16           2          5
    17           7          6
    18          22          5
    19          22          6
    20          23          9
    21          23          5
    22          14          4
    23          14          1
    24          11         10
    25          42          9
    26          50          8
    27          38          1

In [6]:
pd.concat([reg_01,reg_02],axis=1)

    student_id  course_id  student_id  course_id
0         23.0        1.0           3          5
1         15.0        5.0          16          7
2         18.0        6.0          12         10
3         23.0        4.0          12          1
4         16.0        9.0          14          9
5         18.0        1.0           7          7
6          1.0        1.0           7          2
7          7.0        8.0          16          3
8         22.0        3.0          17         10
9         15.0        1.0          11          8
10        19.0        4.0          14          6
11         1.0        6.0          12          5
12         7.0       10.0          12          7
13        11.0        7.0          18          8
14        13.0        3.0           1         10
15        24.0        4.0           1          9
16        21.0        1.0           2          5
17        16.0        5.0           7          6
18        23.0        3.0          22          5
19        17.0        7.0          22          6
20        23.0        6.0          23          9
21        25.0        1.0          23          5
22        19.0        2.0          14          4
23        25.0       10.0          14          1
24         3.0        3.0          11         10
25         NaN        NaN          42          9
26         NaN        NaN          50          8
27         NaN        NaN          38          1

In [7]:
#Inner Join 

students.merge(reg_01,how='inner',on='student_id')

    student_id                name  partner  course_id
0            1       Kailash Harjo       23          1
1            1       Kailash Harjo       23          6
2            3      Parveen Bhalla        3          3
3            7        Tarun Thaker        9          8
4            7        Tarun Thaker        9         10
5           11  David Mukhopadhyay       20          7
6           13      Munni Varghese       24          3
7           15           Preet Sha       16          5
8           15           Preet Sha       16          1
9           16        Elias Dodiya       25          9
10          16        Elias Dodiya       25          5
11          17        Yasmin Palan        7          7
12          18     Fardeen Mahabir       13          6
13          18     Fardeen Mahabir       13          1
14          19        Qabeel Raman       12          4
15          19        Qabeel Raman       12          2
16          21          Seema Kota       15          1
17          22          Yash Sethi       21          3
18          23      Chhavi Lachman       18          1
19          23      Chhavi Lachman       18          4
20          23      Chhavi Lachman       18          3
21          23      Chhavi Lachman       18          6
22          24        Radhika Suri       17          4
23          25     Shashank D’Alia        2          1
24          25     Shashank D’Alia        2         10

In [12]:
# Total Revenue Generated by Company

reg_01

    student_id  course_id
0           23          1
1           15          5
2           18          6
3           23          4
4           16          9
5           18          1
6            1          1
7            7          8
8           22          3
9           15          1
10          19          4
11           1          6
12           7         10
13          11          7
14          13          3
15          24          4
16          21          1
17          16          5
18          23          3
19          17          7
20          23          6
21          25          1
22          19          2
23          25         10
24           3          3