In [1]:
import pandas as pd

In [2]:
dict1 ={'Name':['Priyang','Aadhya','Krisha','Vedant','Parshv',
                'Mittal','Archana'],
                'Marks':[98,89,99,87,90,83,99],
                'Gender':['Male','Female','Female','Male','Male',
                         'Female','Female']
               }

df1=pd.DataFrame(dict1)
df1

      Name  Marks  Gender
0  Priyang     98    Male
1   Aadhya     89  Female
2   Krisha     99  Female
3   Vedant     87    Male
4   Parshv     90    Male
5   Mittal     83  Female
6  Archana     99  Female

#### 
1. Check first 3 rows
2. check last 3 rows
3. find shape of dataframe (rows, col)
4. get information about df
5. check null values
6. get overall statistics
7. find unique values from gender column
8. find no. of unique values from gender column
9. display count of individual unique values in gender col
10. find total no. of students having marks b/w 90 to 100 (inclusive), using between method
11. find avg marks
12. apply method (use to make a new col of half marks)
13. Map function (use to make a new col labelled 'Male_female'; use 1 for male and 0 for female)
14. drop column(s)
15. print name of cols
16. sort by marks
17. display marks and name of female students

In [4]:
#1

df1.head(3)

      Name  Marks  Gender
0  Priyang     98    Male
1   Aadhya     89  Female
2   Krisha     99  Female

In [5]:
#2 

df1.tail(3)

      Name  Marks  Gender
4   Parshv     90    Male
5   Mittal     83  Female
6  Archana     99  Female

In [7]:
#3
df1.shape

(7, 3)

In [11]:
#4

df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    7 non-null      object
 1   Marks   7 non-null      int64
 2   Gender  7 non-null      object
dtypes: int64(1), object(2)
memory usage: 300.0+ bytes

In [18]:
#5
df1.isnull().count()

Name      7
Marks     7
Gender    7
dtype: int64

In [21]:
#6

df1.describe()

           Marks
count   7.000000
mean   92.142857
std     6.491753
min    83.000000
25%    88.000000
50%    90.000000
75%    98.500000
max    99.000000

In [27]:
#7 

df1['Gender'].unique()

array(['Male', 'Female'], dtype=object)

In [32]:
#8
df1['Gender'].nunique()

2

In [34]:
#9
df1['Gender'].value_counts()

Gender
Female    4
Male      3
Name: count, dtype: int64

In [42]:
#10
df1[(df1['Marks'] >= 90) & (df1['Marks'] <= 100)]

      Name  Marks  Gender
0  Priyang     98    Male
2   Krisha     99  Female
4   Parshv     90    Male
6  Archana     99  Female

In [43]:
#11
df1['Marks'].mean()

92.14285714285714

In [ ]:
#14

df1.drop('Gender',inplace=True)

In [24]:
#15

df1.columns

Index(['Name', 'Marks', 'Gender'], dtype='object')

In [52]:
#16
df1.sort_values('Marks')

      Name  Marks  Gender
5   Mittal     83  Female
3   Vedant     87    Male
1   Aadhya     89  Female
4   Parshv     90    Male
0  Priyang     98    Male
2   Krisha     99  Female
6  Archana     99  Female

In [50]:
#17

df1[df1['Gender'] == 'Female'][['Name','Marks']]

      Name  Marks
1   Aadhya     89
2   Krisha     99
5   Mittal     83
6  Archana     99