In [1]:
pip install kagglehub

Requirement already satisfied: kagglehub in c:\users\ronitjadhav\anaconda3\lib\site-packages (1.0.2)
Requirement already satisfied: kagglesdk<1.0,>=0.1.22 in c:\users\ronitjadhav\anaconda3\lib\site-packages (from kagglehub) (0.1.37)
Requirement already satisfied: packaging in c:\users\ronitjadhav\anaconda3\lib\site-packages (from kagglehub) (24.1)
Requirement already satisfied: pyyaml in c:\users\ronitjadhav\anaconda3\lib\site-packages (from kagglehub) (6.0.1)
Requirement already satisfied: requests in c:\users\ronitjadhav\anaconda3\lib\site-packages (from kagglehub) (2.32.3)
Requirement already satisfied: tqdm in c:\users\ronitjadhav\anaconda3\lib\site-packages (from kagglehub) (4.66.5)
Requirement already satisfied: protobuf in c:\users\ronitjadhav\anaconda3\lib\site-packages (from kagglesdk<1.0,>=0.1.22->kagglehub) (4.25.3)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\ronitjadhav\anaconda3\lib\site-packages (from requests->kagglehub) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\ronitjadhav\anaconda3\lib\site-packages (from requests->kagglehub) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\ronitjadhav\anaconda3\lib\site-packages (from requests->kagglehub) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\ronitjadhav\anaconda3\lib\site-packages (from requests->kagglehub) (2024.8.30)
Requirement already satisfied: colorama in c:\users\ronitjadhav\anaconda3\lib\site-packages (from tqdm->kagglehub) (0.4.6)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import os
import kagglehub
import pandas as pd

# Download latest version of the dataset
path = kagglehub.dataset_download("lava18/google-play-store-apps")
print("Path to dataset files:", path)

# List the files inside the downloaded folder to get the exact CSV filename
files = os.listdir(path)
print("Files downloaded:", files)

# Load the main CSV file into a Pandas DataFrame
csv_file_path = os.path.join(path, "googleplaystore.csv")
df = pd.read_csv(csv_file_path)

# Preview the data
df.head()

Downloading to C:\Users\RonitJadhav\.cache\kagglehub\datasets\lava18\google-play-store-apps\6.archive...

100%|██████████| 1.94M/1.94M [00:01<00:00, 1.28MB/s]

Extracting files...
Path to dataset files: C:\Users\RonitJadhav\.cache\kagglehub\datasets\lava18\google-play-store-apps\versions\6
Files downloaded: ['googleplaystore.csv', 'googleplaystore_user_reviews.csv', 'license.txt']

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up

In [4]:
df.head(5)

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up

In [5]:
df.tail(5)

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
10836,Sya9a Maroc - FR,FAMILY,4.5,38,53M,"5,000+",Free,0,Everyone,Education,"July 25, 2017",1.48,4.1 and up
10837,Fr. Mike Schmitz Audio Teachings,FAMILY,5.0,4,3.6M,100+,Free,0,Everyone,Education,"July 6, 2018",1.0,4.1 and up
10838,Parkinson Exercices FR,MEDICAL,NaN,3,9.5M,"1,000+",Free,0,Everyone,Medical,"January 20, 2017",1.0,2.2 and up
10839,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.5,114,Varies with device,"1,000+",Free,0,Mature 17+,Books & Reference,"January 19, 2015",Varies with device,Varies with device
10840,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,4.5,398307,19M,"10,000,000+",Free,0,Everyone,Lifestyle,"July 25, 2018",Varies with device,Varies with device

In [6]:
df.shape

(10841, 13)

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10841 entries, 0 to 10840
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             10841 non-null  object
 1   Category        10841 non-null  object
 2   Rating          9367 non-null   float64
 3   Reviews         10841 non-null  object
 4   Size            10841 non-null  object
 5   Installs        10841 non-null  object
 6   Type            10840 non-null  object
 7   Price           10841 non-null  object
 8   Content Rating  10840 non-null  object
 9   Genres          10841 non-null  object
 10  Last Updated    10841 non-null  object
 11  Current Ver     10833 non-null  object
 12  Android Ver     10838 non-null  object
dtypes: float64(1), object(12)
memory usage: 1.1+ MB

In [11]:
df.describe()

            Rating
count  9367.000000
mean      4.193338
std       0.537431
min       1.000000
25%       4.000000
50%       4.300000
75%       4.500000
max      19.000000

In [34]:
#6. Total Number of App Titles Contain Astrology
df['App'].str.contains('Astrology',case=False,na=False).sum()

3

In [41]:
df[df['App'].str.contains('Astrology', case=False, na=False)]['App']

1570     Horoscopes – Daily Zodiac Horoscope and Astrology
1592                သိင်္ Astrology - Min Thein Kha BayDin
10840        iHoroscope - 2018 Daily Horoscope & Astrology
Name: App, dtype: object

In [ ]:
#7 Find Average App Rating
df['Rating'].median()

4.3

In [46]:
#8  Find Total Number of Unique Category
df['Category'].nunique()

34

In [52]:
#9. Which Category Getting The Highest Average Rating?
hgihtest_average = df[df['Category'] == df['Rating'].mean()]

In [53]:
hgihtest_average

Empty DataFrame
Columns: [App, Category, Rating, Reviews, Size, Installs, Type, Price, Content Rating, Genres, Last Updated, Current Ver, Android Ver]
Index: []

In [50]:
#10. Find Total Number of App having 5 Star Rating
five_star = df[df['Rating'] == 5.0]

five_star.shape[0]

274

In [27]:
#11 Find Average Value of Reviews

df.head(1)

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up

In [ ]:
#12. Find Total Number of Free and Paid Apps
df['Type']

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up